# Run from project root:  powershell -ExecutionPolicy Bypass -File scripts/fix-postgres-migrations.ps1
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

Write-Host "Removing old SQLite migration folders..."
Get-ChildItem "prisma\migrations" -Directory | Where-Object {
    $_.Name -ne "20260422000000_init_postgresql"
} | ForEach-Object {
    Write-Host "  delete $($_.Name)"
    Remove-Item $_.FullName -Recurse -Force
}

$lock = "prisma\migrations\migration_lock.toml"
@(
    "# Please do not edit this file manually",
    "# It should be added in your version-control system (i.e. Git)",
    'provider = "postgresql"',
    ""
) | Set-Content -Path $lock -Encoding UTF8

Write-Host "Migration folders left:"
Get-ChildItem "prisma\migrations" -Recurse | ForEach-Object { $_.FullName }

Write-Host ""
Write-Host "Running: npx prisma migrate deploy"
npx prisma migrate deploy

Write-Host "Running: npx prisma generate"
npx prisma generate

Write-Host "Running: npm run db:seed"
npm run db:seed

Write-Host "Done."
